name: Deploy Firebase Functions

on:
  workflow_call:
    inputs:
      function-name:
        description: 'Name of the Firebase function to deploy'
        required: true
        type: string
      projects:
        description: 'Comma-separated list of projects'
        required: true
        type: string
      target-bucket:
        description: 'Target bucket for the function'
        required: true
        type: string
    secrets:
      GCP_SA_KEY:
        required: true

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Convert comma-separated projects to matrix
        id: set-matrix
        run: |
          PROJECTS="${{ inputs.projects }}"
          JSON=$(echo "$PROJECTS" | tr -d ' ' | tr ',' '\n' | jq -R . | jq -s '{project: .}')
          echo "matrix=$JSON" >> $GITHUB_OUTPUT

  deploy:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Create .env file
        run: |
          cd functions
          echo "TARGET_BUCKET=${{ inputs.target-bucket }}" > .env

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Deploy Firebase Functions to project ${{ matrix.project }}
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp-key.json"
          firebase deploy --only functions:${{ inputs.function-name }} --project=${{ matrix.project }} --force

      - name: Ensure artifact cleanup policy is set for ${{ matrix.project }}
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp-key.json"
          firebase functions:artifacts:setpolicy \
            --project=${{ matrix.project }} \
            --location=us-central1 || true