name: Deploy Firebase Functions

on:
  workflow_dispatch:
    # inputs:
    #   target-bucket:
    #     type: string
    #     required: true
    #   function-name:
    #     type: string
    #     required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [fitnessai-api, allstays-appex]  # hardcoded for now
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Create .env file
        run: |
          cd functions
          echo "TARGET_BUCKET=appex_app_payloads" > .env

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Deploy Firebase Functions to project ${{ matrix.project }}
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp-key.json"
          firebase deploy --only functions:savePayload --project=${{ matrix.project }}